# Generated by Django 4.0 on 2021-12-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_employee_count_company_founded_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_avatar',
            field=models.ImageField(blank=True, default='company_avatar.png', null=True, upload_to=''),
        ),
    ]
