# Generated by Django 4.0 on 2022-01-11 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_company_address_company_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone_number',
        ),
    ]
