# Generated by Django 4.0 on 2022-01-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_company_created_at_company_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyjob',
            name='salary_range_end',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='companyjob',
            name='salary_range_start',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
