# Generated by Django 4.0 on 2022-01-13 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_companyjobposting_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('attachment', models.FileField(null=True, upload_to='')),
                ('job_posting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_posting_attachments', to='companies.companyjobposting')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
