# Generated by Django 4.0 on 2022-01-13 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_jobpostingattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyjobposting',
            name='company',
        ),
        migrations.RemoveField(
            model_name='jobpostingattachment',
            name='job_posting',
        ),
        migrations.DeleteModel(
            name='CompanyJobApplicant',
        ),
        migrations.DeleteModel(
            name='CompanyJobPosting',
        ),
        migrations.DeleteModel(
            name='JobPostingAttachment',
        ),
    ]
