# Generated by Django 4.0 on 2022-01-13 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_alter_applicantattachment_attachment_and_more'),
        ('companies', '0013_remove_companyjobposting_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyJobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('job_title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('vacancy', models.IntegerField(blank=True, default=1, null=True)),
                ('salary_range_start', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_range_end', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_jobs', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobPostingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('attachment', models.FileField(null=True, upload_to='')),
                ('job_posting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_posting_attachments', to='jobs.companyjobposting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyJobApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('interview', 'For Interview'), ('hired', 'Hired'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_jobs', to='users.applicant')),
                ('company_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_jobs', to='jobs.companyjobposting')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
