# Generated by Django 4.0 on 2022-01-13 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_applicantattachment_attachment_and_more'),
        ('jobs', '0002_rename_companyjobapplicant_jobpostingapplicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostingapplicant',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_applicants', to='users.applicant'),
        ),
        migrations.AlterField(
            model_name='jobpostingapplicant',
            name='company_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_applicants', to='jobs.companyjobposting'),
        ),
    ]
