# Generated by Django 4.0 on 2022-01-13 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobpostingapplicant_applicant_and_more'),
    ]

    operations = [

    ]
