# Generated by Django 4.0 on 2022-01-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobpostingattachment_job_posting'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyjobposting',
            name='employment_type',
            field=models.CharField(choices=[('select', 'Select...'), ('full_time', 'Full Time'), ('part_time', 'Part Time'), ('self_employed', 'Self Employed'), ('freelance', 'Freelance'), ('contract', 'Contractual'), ('internship', 'Internship')], default='full_time', max_length=15),
        ),
    ]
