# Generated by Django 4.0 on 2022-01-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_companyjobposting_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyjobposting',
            name='preferred_skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
