# Generated by Django 4.0 on 2022-01-17 12:31

from django.db import migrations, models
import employee_finder.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_companyjobposting_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostingattachment',
            name='attachment',
            field=models.FileField(null=True, upload_to=employee_finder.helpers.get_upload_to),
        ),
    ]
