# Generated by Django 4.0 on 2022-01-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_jobpostingattachment_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostingapplicant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('interview', 'For Interview'), ('hired', 'Hired'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
