# Generated by Django 4.0 on 2022-01-21 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_customuser_is_paid_alter_applicantskill_efficiency'),
        ('payments', '0002_subscriptiontype__type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontype',
            name='_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('semi', 'Semi-annually'), ('annually', 'Annually')], default='monthly', max_length=8),
        ),
        migrations.CreateModel(
            name='UserSubscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('_type', models.CharField(choices=[('monthly', 'Monthly'), ('semi', 'Semi-annually'), ('annually', 'Annually')], default='monthly', max_length=8)),
                ('price', models.FloatField(default=150)),
                ('paid_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('expiry_date', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.customuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
