# Generated by Django 4.0 on 2022-01-21 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_customuser_is_paid_alter_applicantskill_efficiency'),
        ('payments', '0003_alter_subscriptiontype__type_usersubscriptions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSubscriptions',
            new_name='UserSubscription',
        ),
    ]
