# Generated by Django 4.0 on 2022-01-29 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_applicanteducation_degree'),
        ('payments', '0004_rename_usersubscriptions_usersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.customuser'),
        ),
    ]
