# Generated by Django 4.0 on 2022-01-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_rename__type_usersubscription_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
    ]
