# Generated by Django 4.0 on 2021-12-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_status', models.CharField(choices=[('employed', 'Employed'), ('unemployed', 'Unemployed')], default='unemployed', max_length=10)),
                ('resume', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('address', models.TextField(blank=True, max_length=250, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=50, null=True)),
                ('extension', models.CharField(blank=True, max_length=50, null=True)),
                ('headline', models.CharField(blank=True, max_length=250, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('user_avatar', models.ImageField(blank=True, default='user_avatar.png', null=True, upload_to='')),
                ('overview', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('user_type', models.CharField(choices=[('employer', 'Employer'), ('applicant', 'Applicant')], default='applicant', max_length=10)),
                ('is_superadmin', models.BooleanField(default=False, verbose_name='is_superadmin')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_staff', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
