# Generated by Django 4.0 on 2022-01-11 00:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantexperience',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Mobile number format must be: '+639999999999'.", regex='^(\\+\\d{1,3})?,?\\s?\\d{8,13}')]),
        ),
        migrations.AddField(
            model_name='applicantexperience',
            name='reference_person',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='applicantexperience',
            name='end_month',
            field=models.CharField(blank=True, choices=[('select', 'Select...'), ('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], default='select', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='applicantexperience',
            name='end_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
