# Generated by Django 4.0 on 2022-01-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_applicantattachments_applicantattachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicanteducation',
            name='end_month',
            field=models.CharField(choices=[('', '------'), ('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], default='select', max_length=15),
        ),
        migrations.AlterField(
            model_name='applicanteducation',
            name='start_month',
            field=models.CharField(choices=[('', '------'), ('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], default='select', max_length=15),
        ),
        migrations.AlterField(
            model_name='applicantexperience',
            name='end_month',
            field=models.CharField(blank=True, choices=[('', '------'), ('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], default='select', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='applicantexperience',
            name='start_month',
            field=models.CharField(choices=[('', '------'), ('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], default='select', max_length=15),
        ),
    ]
