# Generated by Django 4.0 on 2021-12-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usereducation_applicant_user_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('employer', 'Employer'), ('applicant', 'Applicant')], default='applicant', max_length=10, null=True),
        ),
    ]
