# Generated by Django 4.0 on 2022-01-11 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_applicanteducation_end_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicanteducation',
            old_name='school',
            new_name='school_name',
        ),
        migrations.AddField(
            model_name='applicanteducation',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Mobile number format must be: '+639999999999'.", regex='^(\\+\\d{1,3})?,?\\s?\\d{8,13}')]),
        ),
        migrations.AddField(
            model_name='applicanteducation',
            name='reference_person',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
