# Generated by Django 4.0 on 2021-12-12 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_attachments', to='users.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=250)),
                ('degree', models.CharField(max_length=250)),
                ('start_month', models.CharField(choices=[('select', 'Please Select'), ('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], default='select', max_length=15)),
                ('start_year', models.CharField(max_length=50)),
                ('end_month', models.CharField(choices=[('select', 'Please Select'), ('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], default='select', max_length=15)),
                ('end_year', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_education', to='users.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('start_month', models.CharField(choices=[('select', 'Please Select'), ('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], default='select', max_length=15)),
                ('start_year', models.CharField(max_length=50)),
                ('end_month', models.CharField(choices=[('select', 'Please Select'), ('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], default='select', max_length=15)),
                ('end_year', models.CharField(max_length=50)),
                ('job_position', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('select', 'Please Select'), ('full_time', 'Full Time'), ('part_time', 'Part Time'), ('self_employed', 'Self Employed'), ('freelance', 'Freelance'), ('contract', 'Contractual'), ('internship', 'Internship')], default='select', max_length=15)),
                ('current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_experience', to='users.applicant')),
            ],
        ),
        migrations.RemoveField(
            model_name='userattachments',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserEducation',
        ),
        migrations.RemoveField(
            model_name='userexperience',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserAttachments',
        ),
        migrations.DeleteModel(
            name='UserExperience',
        ),
    ]
