# Generated by Django 4.0 on 2022-01-12 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_school_applicanteducation_school_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicanteducation',
            name='description',
        ),
    ]
