# Generated by Django 4.0 on 2021-12-15 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_token_alter_applicanteducation_end_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantSeminars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.FileField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_seminars', to='users.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantSeminarsAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seminar_attachments', to='users.applicantseminars')),
            ],
        ),
    ]
