# Generated by Django 4.0 on 2022-01-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_applicantattachment_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantskill',
            name='attachment',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='applicantskill',
            name='efficiency',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='1', max_length=12),
        ),
    ]
