# Generated by Django 4.0 on 2022-01-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_applicantseminars_applicantseminarsattachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('select', 'Select...'), ('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='select', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
