# Generated by Django 4.0 on 2022-01-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_applicantskill_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('select', 'Select...'), ('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='select', max_length=10, null=True),
        ),
    ]
