# Generated by Django 4.0 on 2022-01-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_customuser_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
