# Generated by Django 4.0 on 2022-01-16 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_applicant_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicanteducation',
            name='end_month',
            field=models.CharField(choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], default='jan', max_length=15),
        ),
        migrations.AlterField(
            model_name='applicanteducation',
            name='start_month',
            field=models.CharField(choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], default='jan', max_length=15),
        ),
        migrations.AlterField(
            model_name='applicantexperience',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('self_employed', 'Self Employed'), ('freelance', 'Freelance'), ('contract', 'Contractual'), ('internship', 'Internship')], default='select', max_length=15),
        ),
        migrations.AlterField(
            model_name='applicantexperience',
            name='end_month',
            field=models.CharField(blank=True, choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], default='jan', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='applicantexperience',
            name='start_month',
            field=models.CharField(choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], default='jan', max_length=15),
        ),
        migrations.AlterField(
            model_name='applicantskill',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='select', max_length=10, null=True),
        ),
    ]
