# Generated by Django 4.0 on 2022-01-17 12:31

from django.db import migrations, models
import employee_finder.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_applicantattachment_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantseminar',
            name='summary',
            field=models.FileField(blank=True, null=True, upload_to=employee_finder.helpers.get_upload_to),
        ),
        migrations.AlterField(
            model_name='applicantseminarattachment',
            name='attachment',
            field=models.FileField(null=True, upload_to=employee_finder.helpers.get_upload_to),
        ),
        migrations.AlterField(
            model_name='applicantskill',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=employee_finder.helpers.get_upload_to),
        ),
    ]
