# Generated by Django 4.0 on 2022-01-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_applicanteducation_end_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicanteducation',
            name='degree',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
